SENDGRID_USERNAME: themetalsdirectory
SENDGRID_PASSWORD: o8GVm04M
ADMIN_NAME: First User
ADMIN_EMAIL: admin@themetalsdirectory.com
ADMIN_PASSWORD: trend2013
ROLES: [admin, paid_member, member]
STAGING_USERNAME: trend
STAGING_PASSWORD: trend2013
STRIPE_API_KEY: sk_test_Wv99VKOpHbtqKWgshCNH6hF5
STRIPE_PUBLIC_KEY: pk_test_tnWw0lcp88LbFYWoBKkgcDMn
